### ISSUE TITLE
THUMOS14-Kinetics feature FPS.

### ISSUE THREAD

**Issue by sqiangcao99** [wangxiang1230/OadTR#10]
THUMOS14-Kinetics feature is extracted at 4 FPS in IDN. Is your experimental configuration consistent with IDN? In addition, can you provide more details about the feature extraction method?

**Comment by SCZwangxiao** [comment]
> > THUMOS14-Kinetics feature is extracted at 4 FPS in IDN. Is your experimental configuration consistent with IDN? In addition, can you provide more details about the feature extraction method?
> 
> Hi, thanks for your attention to OadTR. We extract feature in its original FPS. And the feature extraction method is [here](https://github.com/yjxiong/anet2016-cuhk).

Could you explain what does 'it' refer to here？If it refers to the video itself, your setting is different from IDN？

**Comment by wangxiang1230** [comment]
> > > THUMOS14-Kinetics feature is extracted at 4 FPS in IDN. Is your experimental configuration consistent with IDN? In addition, can you provide more details about the feature extraction method?
> > 
> > 
> > Hi, thanks for your attention to OadTR. We extract feature in its original FPS. And the feature extraction method is [here](https://github.com/yjxiong/anet2016-cuhk).
> 
> Could you explain what does 'it' refer to here？If it refers to the video itself, your setting is different from IDN？

Thanks for your attention to our OadTR. 4FPS in IDN refers to getting 4 TSN features from one second of video, which may be misleading. Because in fact, each TSN feature is obtained from 6 frames of input, 4x6=24, that is, 24FPS. The original video frame rate is about 24. We extract video frames according to the original frame rate, and get a feature every 6 frames, which is consistent with IDN.
